"""empty message

Revision ID: 923ff6836149
Revises: c981d81f8001
Create Date: 2024-11-01 12:53:20.518315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923ff6836149'
down_revision = 'c981d81f8001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.alter_column('last_seen',
                        existing_type=sa.DateTime(),
                        nullable=True,
                        server_default=sa.func.now())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
